-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 19:17:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CeadIbague
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CeadIbague
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CeadIbague` DEFAULT CHARACTER SET utf8 ;
USE `CeadIbague` ;

-- -----------------------------------------------------
-- Table `CeadIbague`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeadIbague`.`Director` (
  `idDirector` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `DocumentoIdentidad` INT(10) NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `Telefono` INT(13) NULL,
  PRIMARY KEY (`idDirector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeadIbague`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeadIbague`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `telefono` INT(13) NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeadIbague`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeadIbague`.`Horario` (
  `idHorario` INT NOT NULL,
  `fecha` DATE NULL,
  `horaEntrada` TIMESTAMP NULL,
  `horaSalida` TIMESTAMP NULL,
  `idFuncionario` INT(15) NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `fk_Horario_Funcionario1_idx` (`Funcionario_idFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `CeadIbague`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeadIbague`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeadIbague`.`Permiso` (
  `idPermiso` INT NOT NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `motivo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `idFuncionario` INT(15) NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  `Director_idDirector` INT NOT NULL,
  PRIMARY KEY (`idPermiso`),
  INDEX `fk_Permiso_Funcionario1_idx` (`Funcionario_idFuncionario` ASC) VISIBLE,
  INDEX `fk_Permiso_Director1_idx` (`Director_idDirector` ASC) VISIBLE,
  CONSTRAINT `fk_Permiso_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `CeadIbague`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permiso_Director1`
    FOREIGN KEY (`Director_idDirector`)
    REFERENCES `CeadIbague`.`Director` (`idDirector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
